/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef example_CONSTANTS_H
#define example_CONSTANTS_H

#include "example_types.h"

namespace thrift { namespace example {

class exampleConstants {
 public:
  exampleConstants();

  int32_t MAX_RESULTS;
};

extern const exampleConstants g_example_constants;

}} // namespace

#endif
