/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "example_constants.h"

namespace thrift { namespace example {

const exampleConstants g_example_constants;

exampleConstants::exampleConstants() {
  MAX_RESULTS = 100;

}

}} // namespace

