//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./example_types');
//HELPER FUNCTIONS AND STRUCTURES

Twitter_ping_args = function(args) {
};
Twitter_ping_args.prototype = {};
Twitter_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_ping_args.prototype.write = function(output) {
  output.writeStructBegin('Twitter_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_ping_result = function(args) {
};
Twitter_ping_result.prototype = {};
Twitter_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_ping_result.prototype.write = function(output) {
  output.writeStructBegin('Twitter_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_postTweet_args = function(args) {
  this.tweet = null;
  if (args) {
    if (args.tweet !== undefined) {
      this.tweet = args.tweet;
    }
  }
};
Twitter_postTweet_args.prototype = {};
Twitter_postTweet_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.tweet = new ttypes.Tweet();
        this.tweet.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_postTweet_args.prototype.write = function(output) {
  output.writeStructBegin('Twitter_postTweet_args');
  if (this.tweet !== null && this.tweet !== undefined) {
    output.writeFieldBegin('tweet', Thrift.Type.STRUCT, 1);
    this.tweet.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_postTweet_result = function(args) {
  this.success = null;
  this.unavailable = null;
  if (args instanceof ttypes.TwitterUnavailable) {
    this.unavailable = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.unavailable !== undefined) {
      this.unavailable = args.unavailable;
    }
  }
};
Twitter_postTweet_result.prototype = {};
Twitter_postTweet_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.unavailable = new ttypes.TwitterUnavailable();
        this.unavailable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_postTweet_result.prototype.write = function(output) {
  output.writeStructBegin('Twitter_postTweet_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.unavailable !== null && this.unavailable !== undefined) {
    output.writeFieldBegin('unavailable', Thrift.Type.STRUCT, 1);
    this.unavailable.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_searchTweets_args = function(args) {
  this.query = null;
  if (args) {
    if (args.query !== undefined) {
      this.query = args.query;
    }
  }
};
Twitter_searchTweets_args.prototype = {};
Twitter_searchTweets_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.query = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_searchTweets_args.prototype.write = function(output) {
  output.writeStructBegin('Twitter_searchTweets_args');
  if (this.query !== null && this.query !== undefined) {
    output.writeFieldBegin('query', Thrift.Type.STRING, 1);
    output.writeString(this.query);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_searchTweets_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
Twitter_searchTweets_result.prototype = {};
Twitter_searchTweets_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.TweetSearchResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_searchTweets_result.prototype.write = function(output) {
  output.writeStructBegin('Twitter_searchTweets_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_zip_args = function(args) {
};
Twitter_zip_args.prototype = {};
Twitter_zip_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_zip_args.prototype.write = function(output) {
  output.writeStructBegin('Twitter_zip_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Twitter_zip_result = function(args) {
};
Twitter_zip_result.prototype = {};
Twitter_zip_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Twitter_zip_result.prototype.write = function(output) {
  output.writeStructBegin('Twitter_zip_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TwitterClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
TwitterClient.prototype = {};
TwitterClient.prototype.ping = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ping();
};

TwitterClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new Twitter_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TwitterClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Twitter_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
TwitterClient.prototype.postTweet = function(tweet, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_postTweet(tweet);
};

TwitterClient.prototype.send_postTweet = function(tweet) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('postTweet', Thrift.MessageType.CALL, this.seqid);
  var args = new Twitter_postTweet_args();
  args.tweet = tweet;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TwitterClient.prototype.recv_postTweet = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Twitter_postTweet_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.unavailable) {
    return callback(result.unavailable);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('postTweet failed: unknown result');
};
TwitterClient.prototype.searchTweets = function(query, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_searchTweets(query);
};

TwitterClient.prototype.send_searchTweets = function(query) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('searchTweets', Thrift.MessageType.CALL, this.seqid);
  var args = new Twitter_searchTweets_args();
  args.query = query;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TwitterClient.prototype.recv_searchTweets = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Twitter_searchTweets_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('searchTweets failed: unknown result');
};
TwitterClient.prototype.zip = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_zip();
};

TwitterClient.prototype.send_zip = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('zip', Thrift.MessageType.CALL, this.seqid);
  var args = new Twitter_zip_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};
TwitterProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
TwitterProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

TwitterProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new Twitter_ping_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ping(function (err, result) {
    var result = new Twitter_ping_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

TwitterProcessor.prototype.process_postTweet = function(seqid, input, output) {
  var args = new Twitter_postTweet_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.postTweet(args.tweet, function (err, result) {
    var result = new Twitter_postTweet_result((err != null ? err : {success: result}));
    output.writeMessageBegin("postTweet", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

TwitterProcessor.prototype.process_searchTweets = function(seqid, input, output) {
  var args = new Twitter_searchTweets_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.searchTweets(args.query, function (err, result) {
    var result = new Twitter_searchTweets_result((err != null ? err : {success: result}));
    output.writeMessageBegin("searchTweets", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

TwitterProcessor.prototype.process_zip = function(seqid, input, output) {
  var args = new Twitter_zip_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.zip()
}

